env: dmc.hopper.hop
agent: drq
base: sac
auxiliary: ~
steps_per_epoch: 8000
max_ep_len: 1000
evaluation: False

setting:
  frame_stack: 3
  num_sources: 2
  background_dataset_path: ./480p
  difficulty: hard
  dynamic: True
  distract_mode: train
  background: False
  camera: False
  color: False
  color_scale: 0.1
  test_color_scale: 0.5
  camera_scale: 0.1
  test_camera_scale: 0.3
  num_videos: 1

buffer_params:
  capacity: 100000    # 1e5
  nstep: 1 # DEFAULT 
  nstep_of_rsd: 5
  gamma: 0.99
  save_buffer: False
  image_size: 84

agent_base_params:
  num: ~
  action_repeat: ~
  actor_update_freq: 1
  update_to_data: 1
  critic_target_update_freq: 2
  extr_update_via_qfloss: True
  extr_update_freq_via_qfloss: 1

extr_params:
  num_layers: 4
  num_filters: 32
  num_fc: 2
  extr_latent_dim: 50
  extr_tau: 0.05
  targ_extr: False

auxiliary_params: ~

agent_params:
  extr_lr: 5.e-4
  extr_beta: 0.9
  image_pad: ~

algo_params:
  alpha_lr: 5.e-4
  critic_lr: 5.e-4
  critic_beta: 0.9
  critic_type: ensemble
  actor_lr: 5.e-4
  actor_beta: 0.9
  alpha_beta: 0.5
  critic_tau: 0.01
  num_q: 2
  num_targ_q: 2
  hidden_dim: 1024
  l: 2        # The num of hidden layer
  extr_latent_dim: 50

train_params:
  total_steps: 500000    # 500K training steps
  init_steps: 100
  action_repeat: 4
  eval_freq: ~
  test: True
  num_eval_episodes: 10
  save_model: True
  save_model_freq: 5 # 5 epoch
